version: 2
jobs:
    build:
        docker:
            - image: blang/latex:ubuntu
        steps:
            - checkout
            - run:
                name: Generating current version
                command: |
                    pdflatex master.tex && makeglossaries master && pdflatex master.tex
                    mkdir /tmp/artifacts;
                    cp master.pdf /tmp/artifacts/
            - store_artifacts:
                path: /tmp/artifacts